---

x-mysql-host: &mysql-host percona
x-mysql-port: &mysql-port 3306
x-mysql-pwd: &mysql-pwd root
x-mysql-user: &mysql-user root
x-http-host: &http-host servicetester
x-http-port: &http-port 3000
x-persist-volumes: &atndalone-volumes
  - ./data:/var/lib/mysql

services:

  # a standalone userservice database. nothing here is persisted 
  # to the filesystem - use mysql-migration+mysql-persist for that.
  # you don't need to test it, since it's the build stage for 
  # mysql-persist and errors will be caught there, but it is good 
  # for testing the userservice and not leaving a mess behind
  mysql-test:
    image: jsmit257/us-db-mysql-test
    build:
      context: .
      dockerfile: Dockerfile.mysql
    restart: always
    hostname: *mysql-host
    ports:
      - 6033:3306
    environment:
      MYSQL_ROOT_PASSWORD: *mysql-pwd

  mysql-migration:
    image: jsmit257/us-db-mysql-mig
    build:
      context: .
      dockerfile: Dockerfile.mysql
      target: migration
    volumes: *atndalone-volumes
    entrypoint: /var/lib/mysql-files/install-userservice.sh mysqld

  mysql-persist:
    image: percona:ps-8.0.36-28
    # image: jsmit257/us-db-mysql-auto:lkg
    depends_on: [ mysql-migration ]
    restart: always
    hostname: *mysql-host
    volumes: *atndalone-volumes
    environment:
      MYSQL_ROOT_PASSWORD: *mysql-pwd

  serve-mysql:
    image: jsmit257/us-srv-mysql
    build: .
    hostname: *http-host
    ports: [ 3000:3000 ]
    environment:
      US_MYSQL_HOST: *mysql-host
      US_MYSQL_PASSWORD: *mysql-pwd
      US_MYSQL_PORT: *mysql-port
      US_MYSQL_USER: *mysql-user
      US_HTTP_HOST: *http-host
      US_HTTP_PORT: *http-port
