---
version: "3.1"

services:

  mysql:
    image: percona:ps-8.0.29-21
    restart: always
    ports:
      - 3306:6033
    environment:
      MYSQL_ROOT_PASSWORD: root

  schema:
    depends_on:
      - mysql
    # apply a userservice schema to the percona container
    image: userservice-mysql-schema
    build:
      context: .
      dockerfile: Dockerfile.schema
    volumes:
      - ./sql:/root/sql
    environment:
      US_MYSQL_HOST: localhost
      US_MYSQL_PORT: 6033
      US_MYSQL_ROOT_PASSWORD: root
      US_MYSQL_USER: root
    working_dir: /root/sql

  build-serve-mysql:
    # build a specific cmd app, stash the artifact on the local filesystem
    image: serve-mysql
    build: .
      # context: .
      # target: build
    volumes:
      - .:/go/src/build
    working_dir: /go/src/build
    # command: /bin/true

  test-serve-mysql:
    depends_on:
      # - schema
      - build-serve-mysql
    # deploy the app to a slim container and run tests
    image: serve-mysql
    # build:
    #   context: .
    #   target: deploy
    volumes:
      - ./bin:/root/bin
    environment:
      US_MYSQL_HOST: localhost
      US_MYSQL_PORT: 6033
      US_MYSQL_ROOT_PASSWORD: root
      US_MYSQL_USER: root
    working_dir: /root/bin
    command: /root/bin/test-integration
