---

x-mysql-host: &mysql-host percona
x-mysql-port: &mysql-port 3306
x-mysql-pwd: &mysql-pwd root
x-mysql-user: &mysql-user root
x-redis-user: &redis-user redis
x-redis-pass: &redis-pass redis
x-redis-host: &redis-host us-redis
x-redis-port: &redis-port 6379
x-http-host: &http-host servicetester
x-http-port: &http-port 3000
x-persist-volumes: &standalone-volumes
  - ./.data:/var/lib/mysql

services:

  # a standalone userservice database. nothing here is persisted 
  # to the filesystem - use mysql-migration+mysql-persist for that.
  # you don't need to test it, since it's the build stage for 
  # mysql-persist and errors will be caught there, but it is good 
  # for testing the userservice and not leaving a mess behind
  mysql-test:
    image: jsmit257/us-db-mysql-test
    build:
      context: .
      dockerfile: Dockerfile.mysql
    restart: always
    hostname: *mysql-host
    ports:
      - 6033:3306
    environment:
      MYSQL_ROOT_PASSWORD: *mysql-pwd

  mysql-migration:
    image: jsmit257/us-db-mysql-mig
    build:
      context: .
      dockerfile: Dockerfile.mysql
      target: migration
    volumes: *standalone-volumes
    entrypoint: /var/lib/mysql-files/install-userservice.sh mysqld

  mysql-persist:
    image: percona:ps-8.0.36-28
    depends_on: [ mysql-migration ]
    restart: always
    hostname: *mysql-host
    volumes: *standalone-volumes
    environment:
      MYSQL_ROOT_PASSWORD: *mysql-pwd

  serve-mysql:
    image: jsmit257/us-srv-mysql
    build: .
    hostname: *http-host
    ports: [ 3000:3000 ]
    environment:
      US_MYSQL_HOST: *mysql-host
      US_MYSQL_PASSWORD: *mysql-pwd
      US_MYSQL_PORT: *mysql-port
      US_MYSQL_USER: *mysql-user
      US_HTTP_HOST: *http-host
      US_HTTP_PORT: *http-port

  redis:
    image: redis:bookworm
    restart: always
    hostname: *redis-host
    ports: [ 6666:6379 ]

  us-web-test:
    image: jsmit257/us-web-test
    restart: always
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports: [ 8585:80 ]
    environment:
      US_HTTP_HOST: *http-host
      US_HTTP_PORT: *http-port
      US_REDIS_USER: *redis-user
      US_REDIS_PASS: *redis-pass
      US_REDIS_HOST: *redis-host
      US_REDIS_PORT: *redis-port
