---
version: "3.1"

services:

  mysql:
    image: percona:ps-8.0.29-21
    restart: always
    hostname: percona
    volumes: [ .:/go/src/build ]
    ports:
      - 6033:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  schema:
    # it's the same image as mysql, so get the mysql-client basically for free
    image: percona:ps-8.0.29-21
    depends_on: [ mysql ]
    # apply a userservice schema to the percona container
    volumes: [ ./sql:/sql ]
    environment:
      US_MYSQL_HOST: percona
      US_MYSQL_PORT: 3306
      US_MYSQL_ROOT_PASSWORD: root
      US_MYSQL_USER: root
    working_dir: /sql/bin
    command: ./driver

  build-serve-mysql:
    # build a specific cmd app, stash the artifact on the local filesystem
    build:
      context: .
      target: build
    volumes: [ .:/go/src/build ]
    working_dir: /go/src/build

  package-serve-mysql:
    # deploy the app to a slim container for deploy
    build: .
    volumes: [ .:/go/src/build ]
    working_dir: /go/src/build

  test-serve-mysql:
    depends_on: [ schema ]
    image: golang:latest
    volumes: [ .:/go/src/build ]
    environment:
      US_MYSQL_HOST: percona
      US_MYSQL_PORT: 3306
      US_MYSQL_ROOT_PASSWORD: root
      US_MYSQL_USER: root
      US_SERVER_HOST: localhost
      US_SERVER_PORT: 3000
    working_dir: /go/src/build
    command: ./bin/test-integration
